// Generated by CoffeeScript 1.10.0
(function() {
  var EnvVars, Type;

  Type = require('typelet');

  EnvVars = (function() {
    function EnvVars() {
      if (!(this instanceof EnvVars)) {
        return new EnvVars();
      }
    }

    return EnvVars;

  })();

  module.exports = EnvVars;

}).call(this);
